# **Student Number : 2358119**

# **Student Name : Vibek Rana Magar**

# **Group : L6CG19**

# **4) TO - DO - Task**

**4.1) Exercise on Functions:**

Task - 1:
Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_units():
    """Converts between different units of measurement."""
    print("Choose conversion type:")
    print("1. Length (m <-> ft)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (L <-> gal)")

    choice = input("Enter 1, 2, or 3: ")

    try:
        if choice == "1":
            value = float(input("Enter value: "))
            unit = input("Enter unit (m/ft): ").lower()
            if unit == "m":
                print(f"{value} meters = {value * 3.28084} feet")
            elif unit == "ft":
                print(f"{value} feet = {value / 3.28084} meters")
            else:
                print("Invalid unit.")
        elif choice == "2":
            value = float(input("Enter value: "))
            unit = input("Enter unit (kg/lbs): ").lower()
            if unit == "kg":
                print(f"{value} kg = {value * 2.20462} lbs")
            elif unit == "lbs":
                print(f"{value} lbs = {value / 2.20462} kg")
            else:
                print("Invalid unit.")
        elif choice == "3":
            value = float(input("Enter value: "))
            unit = input("Enter unit (L/gal): ").lower()
            if unit == "l":
                print(f"{value} liters = {value * 0.264172} gallons")
            elif unit == "gal":
                print(f"{value} gallons = {value / 0.264172} liters")
            else:
                print("Invalid unit.")
        else:
            print("Invalid choice.")
    except ValueError:
        print("Invalid input. Please enter a number.")

convert_units()

Choose conversion type:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Enter 1, 2, or 3: 1
Enter value: 3
Enter unit (m/ft): m
3.0 meters = 9.84252 feet


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def perform_operation():
    """Performs various mathematical operations on a list of numbers."""
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter 1, 2, 3, or 4: ")

    try:
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
        if not numbers:
            print("List cannot be empty.")
            return

        if choice == "1":
            print(f"Sum: {sum(numbers)}")
        elif choice == "2":
            print(f"Average: {sum(numbers) / len(numbers)}")
        elif choice == "3":
            print(f"Maximum: {max(numbers)}")
        elif choice == "4":
            print(f"Minimum: {min(numbers)}")
        else:
            print("Invalid choice.")
    except ValueError:
        print("Invalid input. Please enter numbers.")

perform_operation()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 2
Enter numbers separated by spaces: 3 4 5 6
Average: 4.5


**4.2) Exercise on List Manipulation:**

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """Returns a new list containing every other element from the original list."""
    return lst[::2]

print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """Returns a sublist from start index to end index (inclusive)."""
    return lst[start:end+1]

print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))

[3, 4, 5]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """Returns the reversed list using slicing."""
    return lst[::-1]

print(reverse_list([1, 2, 3, 4, 5]))

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """Removes the first and last elements from the list."""
    return lst[1:-1]

print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

print(get_last_n([1, 2, 3, 4, 5], 2))

[4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    """Returns every second element from the end, moving backward."""
    return lst[-2::-2]

print(reverse_skip([1, 2, 3, 4, 5, 6]))

[5, 3, 1]


**4.3) Exercise on Nested List:**

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """Flattens a nested list into a single list."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[1, 2], [3, 4], [5]]
print(flatten(nested_list))

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """Extracts a specific element from a nested list given its indices."""
    element = lst
    for index in indices:
        element = element[index]
    return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(access_nested_element(lst, indices))

6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """Calculates the sum of all numbers in a nested list."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))

21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

nested_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(nested_list, elem))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """Finds the maximum element in a nested list."""
    max_value = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))
        else:
            max_value = max(max_value, item)
    return max_value

nested_list = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested_list))

6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [ ]:
def count_occurrences(lst, elem):
    """Counts how many times a specific element appears in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurrences(nested_list, elem))

3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """Flattens a list of lists of lists into a single list."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list))

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nested_list))

3.5


**10) To - Do - NumPy**

1.4.1) Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
# 1. Initialize an empty array with size 2X2.
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)

[[2.99231664e-316 0.00000000e+000]
 [6.59737730e-310 6.67421148e-310]]


In [ ]:
# 2. Initialize an all one array with size 4X2.
import numpy as np
all_one_array = np.ones((4, 2))
print(all_one_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
import numpy as np
fill_array = np.full((3, 3), 7)
print(fill_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
import numpy as np
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_array = np.zeros_like(given_array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [ ]:
# 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
import numpy as np
example_array = np.array([[1, 2, 3], [4, 5, 6]])
ones_array = np.ones_like(example_array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [ ]:
# 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
import numpy as np
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


Problem - 2:

Array Manipulation: Numerical Ranges and Array indexing

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
# 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
import numpy as np
array_range = np.arange(10, 50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
import numpy as np
matrix_values = np.arange(9).reshape(3, 3)
print(matrix_values)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
import numpy as np
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)

0.5247469017348465


In [ ]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values
import numpy as np
random_array = np.random.random((10, 10))
min_value = random_array.min()
max_value = random_array.max()
print(f"Minimum value = {min_value}")
print(f"Maximum value = {max_value}")

Minimum value = 0.0018242593951209862
Maximum value = 0.9963990527143564


In [ ]:
# 6. Create a zero array of size 10 and replace 5th element with 1.
import numpy as np
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7.Reverse an array arr = [1,2,0,0,4,0].
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
# 8. Create a 2d array with 1 on border and 0 inside.
import numpy as np
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 9.Create a 8X8 matrix and fill it with a checkerboard pattern.
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3:

Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
# 1. Add the two array.
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
addition_two_array = x + y
print(addition_two_array)

[[ 6  8]
 [10 13]]


In [ ]:
# 2.Subtract the two array.
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
subtraction_two_array = x - y
print(subtraction_two_array)

[[-4 -4]
 [-4 -3]]


In [ ]:
# 3. Multiply the array with any integers of your choice.
import numpy as np
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
multiplication_two_array = x * 2
print(multiplication_two_array)

[[ 2  4]
 [ 6 10]]


In [ ]:
# 4. Find the square of each element of the array.
import numpy as np
x = np.array([[1, 2], [3, 5]])
square_two_array = x ** 2
print(square_two_array)

[[ 1  4]
 [ 9 25]]


In [ ]:
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print(f"Dot product of v and w = {dot_vw}")
print(f"Dot product of x and v ={dot_xv}")
print(f"Dot product of x and y ={dot_xy}")


Dot product of v and w = 219
Dot product of x and v =[29 77]
Dot product of x and y =[[19 22]
 [50 58]]


In [ ]:
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_xy = np.concatenate((x, y), axis=0)

v = v.reshape(-1, 1)
w = w.reshape(-1, 1)

concat_vw = np.concatenate((v, w), axis=1)

print("Concatenation of x and y along rows:\n", concat_xy)
print("\nConcatenation of v and w along columns:\n", concat_vw)


Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]


In [ ]:
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation successful:\n", concat_xv)
except ValueError as e:
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Explanation:

The shape of x is (2,2) (a 2×2 matrix).
The shape of v is (2,) (a 1D array with 2 elements).
When concatenating along axis=0 (rows), NumPy expects the number of columns to match. x has 2 columns, but v has no explicit column dimension (it's 1D), causing a shape mismatch.

Problem - 4:

Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
# 1. Prove A.A^−1 = I.
import numpy as np

A = np.array([[3, 4], [7, 8]])

A_inv = np.linalg.inv(A)

identity_matrix = np.dot(A, A_inv)

print("A inverse (A⁻¹):\n", A_inv)
print("\nA * A⁻¹:\n", identity_matrix)

I = np.eye(2)
is_identity = np.allclose(identity_matrix, I)

print("\nIs A * A⁻¹ equal to Identity matrix?:", is_identity)


A inverse (A⁻¹):
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A * A⁻¹ equal to Identity matrix?: True


In [ ]:
# 2. Prove AB ̸= BA.
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("\nBA:\n", BA)

is_equal = np.array_equal(AB, BA)

print("\nIs AB equal to BA?:", is_equal)


AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA?: False


In [ ]:
# 3. Prove (AB)^T = B^T A^T.
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute AB
AB = np.dot(A, B)

# Compute (AB)^T
transpose_AB = AB.T

# Compute B^T and A^T
B_T = B.T
A_T = A.T

# Compute B^T A^T
BT_AT = np.dot(B_T, A_T)

print("Transpose of AB ( (AB)^T ):\n", transpose_AB)
print("\nMultiplication of Transposed Matrices ( B^T A^T ):\n", BT_AT)

# Verify if (AB)^T == B^T A^T
is_equal = np.array_equal(transpose_AB, BT_AT)
print("\nIs (AB)^T equal to B^T A^T?:", is_equal)

Transpose of AB ( (AB)^T ):
 [[23 51]
 [13 29]]

Multiplication of Transposed Matrices ( B^T A^T ):
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T?: True


In [ ]:
# Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution for x, y, z:")
print(f"x = {X[0]:.2f}")
print(f"y = {X[1]:.2f}")
print(f"z = {X[2]:.2f}")

Solution for x, y, z:
x = 2.00
y = 1.00
z = -2.00


In [ ]:
# Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution using np.linalg.inv():")
print(f"x = {X[0]:.2f}")
print(f"y = {X[1]:.2f}")
print(f"z = {X[2]:.2f}")

Solution using np.linalg.inv():
x = 2.00
y = 1.00
z = -2.00


10.2) Experiment: How Fast is Numpy?

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [3]:
# Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

import time
import random

# Generate two large lists of size 1,000,000 with random integers
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure time for element-wise addition using list comprehension
start_time = time.time()
result = [a + b for a, b in zip(list1, list2)]
end_time = time.time()

# Print the time taken
time_taken = end_time - start_time
print(f"Time taken for element-wise addition of two lists of size {size}: {time_taken:.6f} seconds")

Time taken for element-wise addition of two lists of size 1000000: 0.044140 seconds


In [4]:
# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

import numpy as np

# Convert lists to NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time for element-wise addition using NumPy
start_time = time.time()
result_np = array1 + array2
end_time = time.time()

# Print the time taken with a clear message
time_taken_np = end_time - start_time
print(f"Time taken for element-wise addition using NumPy arrays of size {size}: {time_taken_np:.6f} seconds")

Time taken for element-wise addition using NumPy arrays of size 1000000: 0.005716 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [5]:
# Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.\

import time
import random

# Generate two large lists of size 1,000,000 with random integers
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure time for element-wise multiplication using list comprehension
start_time = time.time()
result_mul = [a * b for a, b in zip(list1, list2)]
end_time = time.time()

# Print the time taken with a clear message
time_taken_mul = end_time - start_time
print(f"Time taken for element-wise multiplication of two lists of size {size}: {time_taken_mul:.6f} seconds")

Time taken for element-wise multiplication of two lists of size 1000000: 0.062071 seconds


In [6]:
# Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

import numpy as np

# Convert lists to NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time for element-wise multiplication using NumPy
start_time = time.time()
result_np_mul = array1 * array2
end_time = time.time()

# Print the time taken with a clear message
time_taken_np_mul = end_time - start_time
print(f"Time taken for element-wise multiplication using NumPy arrays of size {size}: {time_taken_np_mul:.6f} seconds")

Time taken for element-wise multiplication using NumPy arrays of size 1000000: 0.006431 seconds


3.Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [7]:
# Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

import time
import random

# Generate two large lists of size 1,000,000 with random integers
size = 1_000_000
list1 = [random.randint(1, 100) for _ in range(size)]
list2 = [random.randint(1, 100) for _ in range(size)]

# Measure time for computing dot product using Python lists
start_time = time.time()
dot_product = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()

# Print the time taken with a clear message
time_taken_dot = end_time - start_time
print(f"Time taken for computing dot product using Python lists of size {size}: {time_taken_dot:.6f} seconds")

Time taken for computing dot product using Python lists of size 1000000: 0.133166 seconds


In [8]:
#  Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

import numpy as np
import time

# Generate random NumPy arrays of size 1,000,000
size = 1_000_000
array1 = np.random.randint(1, 100, size)
array2 = np.random.randint(1, 100, size)

# Measure time for computing dot product using NumPy
start_time = time.time()
dot_product_np = np.dot(array1, array2)
end_time = time.time()

# Print the time taken with a clear message
time_taken_np_dot = end_time - start_time
print(f"Time taken for computing dot product using NumPy arrays of size {size}: {time_taken_np_dot:.6f} seconds")

Time taken for computing dot product using NumPy arrays of size 1000000: 0.002278 seconds


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [12]:
# Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

import time
import random

# Generate two random 1000x1000 matrices
size = 1000
matrix1 = [[random.randint(1, 100) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(1, 100) for _ in range(size)] for _ in range(size)]

# Initialize the result matrix with zeros
result_matrix = [[0 for _ in range(size)] for _ in range(size)]

# Measure time for matrix multiplication using Python lists
start_time = time.time()

# Perform matrix multiplication
for i in range(size):
    for j in range(size):
        result_matrix[i][j] = sum(matrix1[i][k] * matrix2[k][j] for k in range(size))

end_time = time.time()

# Print the time taken with a clear message
time_taken_matrix_mul = end_time - start_time
print(f"Time taken for matrix multiplication of two {size}x{size} matrices using Python lists: {time_taken_matrix_mul:.6f} seconds")

Time taken for matrix multiplication of two 1000x1000 matrices using Python lists: 125.495339 seconds


In [13]:
# Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

import numpy as np
import time

# Generate two random 1000x1000 matrices
size = 1000
matrix1 = np.random.randint(1, 100, (size, size))
matrix2 = np.random.randint(1, 100, (size, size))

# Measure time for matrix multiplication using NumPy
start_time = time.time()
result_matrix_np = np.dot(matrix1, matrix2)
end_time = time.time()

# Print the time taken with a clear message
time_taken_matrix_mul_np = end_time - start_time
print(f"Time taken for matrix multiplication of two {size}x{size} matrices using NumPy arrays: {time_taken_matrix_mul_np:.6f} seconds")

Time taken for matrix multiplication of two 1000x1000 matrices using NumPy arrays: 4.735391 seconds
